# Generated by Django 6.0.3 on 2026-03-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_user_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Auto-generated ID: CAT-P001, CAT-I001, etc.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., 'Bread', 'Flour')",
                        max_length=100,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Product", "Product"), ("Ingredient", "Ingredient")],
                        help_text="Category type: Product or Ingredient",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of category",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "api_category",
                "ordering": ["type", "name"],
                "indexes": [
                    models.Index(
                        fields=["category_id"], name="api_categor_categor_c3f6e9_idx"
                    ),
                    models.Index(fields=["type"], name="api_categor_type_daa808_idx"),
                    models.Index(fields=["name"], name="api_categor_name_53a3ad_idx"),
                    models.Index(
                        fields=["type", "name"], name="api_categor_type_212437_idx"
                    ),
                ],
                "unique_together": {("type", "name")},
            },
        ),
    ]
