# Generated by Django 6.0.3 on 2026-03-23 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingredient_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated: #I001, #I002, etc.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'All Purpose Flour', 'Granulated Sugar'",
                        max_length=100,
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True,
                        help_text="Supplier company name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "supplier_contact",
                    models.CharField(
                        blank=True,
                        help_text="Supplier phone/email",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tracking_type",
                    models.CharField(
                        choices=[
                            ("Weight", "Weight (kg, g)"),
                            ("Volume", "Volume (liters, ml)"),
                            ("Count", "Count (pieces, units)"),
                        ],
                        default="Weight",
                        help_text="How this ingredient is tracked (by weight, volume, or count)",
                        max_length=20,
                    ),
                ),
                (
                    "base_unit",
                    models.CharField(
                        help_text="e.g., 'kg', 'liters', 'pieces'", max_length=20
                    ),
                ),
                (
                    "total_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total quantity from active batches (updated via signals, READ-ONLY)",
                        max_digits=10,
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        help_text="Alert threshold for low stock",
                        max_digits=10,
                    ),
                ),
                (
                    "shelf_life",
                    models.IntegerField(
                        default=30,
                        help_text="Number of days/weeks/months before expiry",
                    ),
                ),
                (
                    "shelf_unit",
                    models.CharField(
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        default="days",
                        help_text="Unit for shelf life (days, weeks, months)",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft delete support - set to False instead of deleting",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category_id",
                    models.ForeignKey(
                        help_text="Must be an Ingredient-type category",
                        limit_choices_to={"type": "Ingredient"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingredients",
                        to="api.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingredient",
                "verbose_name_plural": "Ingredients",
                "ordering": ["category_id", "name"],
                "indexes": [
                    models.Index(
                        fields=["ingredient_id"], name="api_ingredi_ingredi_02b0de_idx"
                    ),
                    models.Index(
                        fields=["category_id"], name="api_ingredi_categor_2cd338_idx"
                    ),
                    models.Index(fields=["name"], name="api_ingredi_name_ed215b_idx"),
                    models.Index(
                        fields=["category_id", "name"],
                        name="api_ingredi_categor_2980eb_idx",
                    ),
                    models.Index(
                        fields=["is_active", "total_quantity"],
                        name="api_ingredi_is_acti_02194d_idx",
                    ),
                ],
                "unique_together": {("category_id", "name")},
            },
        ),
    ]
