# Generated by Django 6.0.3 on 2026-03-23 13:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_ingredient"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated: BATCH-1001, BATCH-1002, etc.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total quantity received for this batch",
                        max_digits=10,
                    ),
                ),
                (
                    "current_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current remaining quantity in this batch",
                        max_digits=10,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost per unit (optional for financial tracking)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "made_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date batch was received/created",
                    ),
                ),
                (
                    "expire_date",
                    models.DateTimeField(help_text="Expiry date for this batch"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Expired", "Expired"),
                            ("Used", "Used"),
                        ],
                        db_index=True,
                        default="Active",
                        help_text="Current status of the batch",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ingredient_id",
                    models.ForeignKey(
                        help_text="Ingredient this batch belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="api.ingredient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingredient Batch",
                "verbose_name_plural": "Ingredient Batches",
                "ordering": ["expire_date", "made_date"],
                "indexes": [
                    models.Index(
                        fields=["ingredient_id", "status"],
                        name="api_ingredi_ingredi_00a6f9_idx",
                    ),
                    models.Index(
                        fields=["expire_date"], name="api_ingredi_expire__9fe28a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="api_ingredi_status_616b7a_idx"
                    ),
                    models.Index(
                        fields=["batch_id"], name="api_ingredi_batch_i_8ef041_idx"
                    ),
                ],
            },
        ),
    ]
