# Generated by Django 6.0.3 on 2026-03-23 16:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=2, help_text='Quantity of ingredient needed (in base unit)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_id', 'created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='api_product_product_aec78f_idx',
            old_name='api_product_product_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='api_product_categor_fb2459_idx',
            old_name='api_product_cat_name_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='api_product_created_a91d70_idx',
            old_name='api_product_created_idx',
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='ingredient_id',
            field=models.ForeignKey(help_text='Ingredient required for product', on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='api.ingredient'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='product_id',
            field=models.ForeignKey(help_text='Product this recipe belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='api.product'),
        ),
        migrations.AddIndex(
            model_name='recipeitem',
            index=models.Index(fields=['product_id'], name='api_recipei_product_69dd07_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeitem',
            index=models.Index(fields=['ingredient_id'], name='api_recipei_ingredi_d88b43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeitem',
            unique_together={('product_id', 'ingredient_id')},
        ),
    ]
