# Generated by Django 6.0.3 on 2026-03-24 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_recipeitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "discount_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("Percentage", "Percentage (%)"),
                            ("FixedAmount", "Fixed Amount (Rs)"),
                        ],
                        default="Percentage",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="For Percentage: 0-100, For FixedAmount: any positive number",
                        max_digits=10,
                    ),
                ),
                (
                    "applicable_to",
                    models.CharField(
                        choices=[
                            ("All", "All Products"),
                            ("Category", "Specific Category"),
                            ("Product", "Specific Product"),
                        ],
                        default="All",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_category_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discounts",
                        to="api.category",
                    ),
                ),
                (
                    "target_product_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discounts",
                        to="api.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["discount_id"], name="api_discoun_discoun_029348_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="api_discoun_is_acti_474f9e_idx"
                    ),
                    models.Index(
                        fields=["applicable_to"], name="api_discoun_applica_72bec4_idx"
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="api_discoun_start_d_2bb812_idx",
                    ),
                ],
            },
        ),
    ]
