# Generated by Django 6.0.3 on 2026-03-24 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_sale_saleitem_sale_api_sale_bill_nu_ab6ba0_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductStockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("AddStock", "Add Stock (Production/Batch)"),
                            ("UseStock", "Use Stock (Sale)"),
                            ("ReturnStock", "Return Stock (Product Return)"),
                            ("WasteStock", "Waste Stock (Spoilage/Damage)"),
                            (
                                "StockAdjustment",
                                "Stock Adjustment (Inventory Correction)",
                            ),
                        ],
                        db_index=True,
                        help_text="Type of stock change",
                        max_length=20,
                    ),
                ),
                (
                    "qty_before",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Stock quantity before transaction",
                        max_digits=10,
                    ),
                ),
                (
                    "qty_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Stock quantity after transaction",
                        max_digits=10,
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Change in quantity (positive for additions, negative for removals)",
                        max_digits=10,
                    ),
                ),
                (
                    "sale_bill_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Bill number if this is from a sale",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the transaction",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_history",
                        to="api.product",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the change (cashier, storekeeper, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Stock History",
                "verbose_name_plural": "Product Stock Histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product_id", "-created_at"],
                        name="api_product_product_17f379_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "-created_at"],
                        name="api_product_transac_f3869f_idx",
                    ),
                    models.Index(
                        fields=["sale_bill_number"],
                        name="api_product_sale_bi_7d8f8a_idx",
                    ),
                ],
            },
        ),
    ]
