# Generated by Django 6.0.3 on 2026-03-24 16:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_productstockhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated: PROD-BATCH-1001, PROD-BATCH-1002, etc.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total quantity produced in this batch",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "made_date",
                    models.DateField(help_text="Date when batch was produced"),
                ),
                (
                    "expire_date",
                    models.DateField(
                        help_text="Date when batch expires (auto-calculated: made_date + product.shelf_life)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Expired", "Expired"),
                            ("Used", "Used"),
                        ],
                        db_index=True,
                        default="Active",
                        help_text="Active, Expired, or Used",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about production e.g., 'Oven #2', 'Made by Baker1'",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        help_text="Product this batch is made of",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="api.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-made_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["batch_id"], name="api_product_batch_i_a17d01_idx"
                    ),
                    models.Index(
                        fields=["product_id", "-made_date"],
                        name="api_product_product_ec1162_idx",
                    ),
                    models.Index(
                        fields=["expire_date"], name="api_product_expire__fa2bd0_idx"
                    ),
                    models.Index(
                        fields=["status"], name="api_product_status_5d3f9f_idx"
                    ),
                ],
            },
        ),
    ]
