# Generated by Django 6.0.3 on 2026-03-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_productbatch"),
    ]

    operations = [
        migrations.CreateModel(
            name="WastageReason",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "reason_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("reason", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["reason_id"],
                "indexes": [
                    models.Index(
                        fields=["reason_id"], name="api_wastage_reason__43a890_idx"
                    ),
                    models.Index(
                        fields=["reason"], name="api_wastage_reason_a2d5af_idx"
                    ),
                ],
            },
        ),
    ]
