# Generated by Django 6.0.3 on 2026-03-25 07:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_create_wastage_reason_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductWastage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wastage_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated ID: PW-001, PW-002, etc.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity of product wasted",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit at time of wastage",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "total_loss",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Calculated as quantity * unit_cost",
                        max_digits=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the wastage",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when wastage was recorded",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of last update"
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        help_text="The product that was wasted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wastage_records",
                        to="api.product",
                    ),
                ),
                (
                    "reason_id",
                    models.ForeignKey(
                        help_text="Reason for wastage",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_wastages",
                        to="api.wastagereason",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        help_text="User who reported the wastage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_wastages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Wastage",
                "verbose_name_plural": "Product Wastages",
                "db_table": "api_product_wastage",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wastage_id"], name="api_product_wastage_f6f1a0_idx"
                    ),
                    models.Index(
                        fields=["product_id"], name="api_product_product_3778a5_idx"
                    ),
                    models.Index(
                        fields=["reason_id"], name="api_product_reason__8442be_idx"
                    ),
                    models.Index(
                        fields=["reported_by"], name="api_product_reporte_2fa545_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="api_product_created_342a3b_idx"
                    ),
                ],
            },
        ),
    ]
