# Generated by Django 6.0.3 on 2026-03-25 08:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_create_product_wastage_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientWastage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wastage_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated ID: IW-001, IW-002, etc.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity of ingredient wasted",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit at time of wastage",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "total_loss",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Calculated as quantity * unit_cost",
                        max_digits=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the wastage",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when wastage was recorded",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of last update"
                    ),
                ),
                (
                    "batch_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="The batch from which wastage occurred (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wastage_records",
                        to="api.ingredientbatch",
                    ),
                ),
                (
                    "ingredient_id",
                    models.ForeignKey(
                        help_text="The ingredient that was wasted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wastage_records",
                        to="api.ingredient",
                    ),
                ),
                (
                    "reason_id",
                    models.ForeignKey(
                        help_text="Reason for wastage",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingredient_wastages",
                        to="api.wastagereason",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        help_text="User who reported the wastage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_ingredient_wastages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingredient Wastage",
                "verbose_name_plural": "Ingredient Wastages",
                "db_table": "api_ingredient_wastage",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wastage_id"], name="api_ingredi_wastage_dce494_idx"
                    ),
                    models.Index(
                        fields=["ingredient_id"], name="api_ingredi_ingredi_b0819d_idx"
                    ),
                    models.Index(
                        fields=["batch_id"], name="api_ingredi_batch_i_5b292c_idx"
                    ),
                    models.Index(
                        fields=["reason_id"], name="api_ingredi_reason__96a027_idx"
                    ),
                    models.Index(
                        fields=["reported_by"], name="api_ingredi_reporte_823dec_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="api_ingredi_created_305c24_idx"
                    ),
                ],
            },
        ),
    ]
