# Generated by Django 6.0.3 on 2026-03-25 09:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_ingredientwastage"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientStockHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("AddStock", "Add Stock"),
                            ("UseStock", "Use Stock"),
                            ("Wastage", "Wastage"),
                            ("Adjustment", "Adjustment"),
                        ],
                        help_text="Type of transaction",
                        max_length=20,
                    ),
                ),
                (
                    "qty_before",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity before transaction",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "qty_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity after transaction",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Change in quantity (positive or negative)",
                        max_digits=10,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of related transaction (IngredientBatch, IngredientWastage, etc.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the transaction",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific batch involved (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_history",
                        to="api.ingredientbatch",
                    ),
                ),
                (
                    "ingredient_id",
                    models.ForeignKey(
                        help_text="Ingredient whose stock changed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_history",
                        to="api.ingredient",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingredient_stock_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api_ingredient_stock_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ingredient_id"], name="api_ingredi_ingredi_d2b3a4_idx"
                    ),
                    models.Index(
                        fields=["batch_id"], name="api_ingredi_batch_i_d30584_idx"
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="api_ingredi_transac_0f2620_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="api_ingredi_created_00d7ea_idx"
                    ),
                    models.Index(
                        fields=["ingredient_id", "-created_at"],
                        name="api_ingredi_ingredi_85a525_idx",
                    ),
                ],
            },
        ),
    ]
