# Generated by Django 6.0.3 on 2026-03-25 10:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_ingredientstockhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LowStock", "Low Stock Alert"),
                            ("Expiry", "Expiry Alert"),
                            ("HighWastage", "High Wastage Alert"),
                            ("OutOfStock", "Out of Stock Alert"),
                            ("System", "System Alert"),
                            ("Warning", "Warning"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="info", max_length=50, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["type"], name="api_notific_type_f8c324_idx"),
                    models.Index(
                        fields=["created_at"], name="api_notific_created_238c70_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="api.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="api_notific_user_id_706d4e_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="api_notific_user_id_81e961_idx",
                    ),
                    models.Index(
                        fields=["is_read"], name="api_notific_is_read_a32686_idx"
                    ),
                ],
                "unique_together": {("notification", "user")},
            },
        ),
    ]
