# Generated by Django 6.0.3 on 2026-03-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_notification_notificationreceipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="low_stock_alert",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Quantity threshold for low stock alerts (for Product categories)",
                null=True,
            ),
        ),
    ]
