# Generated by Django 6.0.3 on 2026-03-29 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_low_stock_alert_to_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='product_id',
            field=models.ForeignKey(blank=True, help_text='Product sold (null if product was deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='api.product'),
        ),
    ]
