# Generated by Django 6.0.3 on 2026-03-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_alter_saleitem_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationreceipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("unread", "Unread"),
                    ("read", "Read"),
                    ("snoozed", "Snoozed"),
                ],
                default="unread",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationreceipt",
            index=models.Index(
                fields=["user", "status"], name="api_notific_user_id_856416_idx"
            ),
        ),
    ]
