# Generated by Django 6.0.3 on 2026-03-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_notificationreceipt_status_alter_saleitem_product_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationreceipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("unread", "Unread"),
                    ("read", "Read"),
                    ("snoozed", "Snoozed"),
                    ("archived", "Archived"),
                ],
                default="unread",
                max_length=20,
            ),
        ),
    ]
