# Generated by Django 6.0.3 on 2026-04-01 10:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_notificationreceipt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='current_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Current quantity remaining in batch (tracks consumption/usage)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='productwastage',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='The product batch this wastage came from (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastage_records', to='api.productbatch'),
        ),
    ]
