# Generated by Django 6.0.3 on 2026-04-01 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_productbatch_current_qty_productwastage_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='product_id',
            field=models.ForeignKey(help_text='Product sold', on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='api.product'),
        ),
    ]
