# Generated by Django 6.0.3 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_saleitem_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationreceipt',
            name='snooze_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notificationreceipt',
            index=models.Index(fields=['user', 'snooze_until'], name='api_notific_user_id_4eb8ee_idx'),
        ),
    ]
