# Generated by Django 6.0.3 on 2026-04-03 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_notificationreceipt_snooze_until"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notificationreceipt",
            new_name="api_notific_user_id_2d7a6c_idx",
            old_name="api_notific_user_id_4eb8ee_idx",
        ),
        migrations.AlterField(
            model_name="ingredientstockhistory",
            name="batch_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific batch involved (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_history",
                to="api.ingredientbatch",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientwastage",
            name="batch_id",
            field=models.ForeignKey(
                blank=True,
                help_text="The batch from which wastage occurred (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wastage_records",
                to="api.ingredientbatch",
            ),
        ),
    ]
