# Generated by Django 6.0.3 on 2026-04-03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_api_notific_user_id_4eb8ee_idx_api_notific_user_id_2d7a6c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_counter_sessions', to='api.user')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_counter_sessions', to='api.user')),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['is_active', 'opened_at'], name='api_counter_is_acti_f3b4bb_idx'), models.Index(fields=['opened_by', 'opened_at'], name='api_counter_opened__2f1938_idx')],
            },
        ),
    ]
