# Generated by Django 6.0.3 on 2026-04-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_countersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='counter_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.countersession'),
        ),
    ]
