# Generated by Django 6.0.3 on 2026-04-03 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_notification_counter_session"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="countersession",
            new_name="api_counter_is_acti_49e9e9_idx",
            old_name="api_counter_is_acti_f3b4bb_idx",
        ),
        migrations.RenameIndex(
            model_name="countersession",
            new_name="api_counter_opened__f8aab5_idx",
            old_name="api_counter_opened__2f1938_idx",
        ),
    ]
