# Generated by Django 6.0.3 on 2026-04-07 07:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_expand_wastage_monetary_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientwastage",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Cost per unit at time of wastage",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="productwastage",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Cost per unit at time of wastage",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
