# Generated by Django 6.0.3 on 2026-04-07 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_alter_ingredientwastage_unit_cost_and_more"),
        ("api", "0031_normalize_legacy_ingredient_thresholds"),
    ]

    operations = []
