# Generated by Django 6.0.3 on 2026-04-07 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_merge_20260407_1421"),
        ("api", "0032_rename_ingredientbatch_cost_field"),
    ]

    operations = []
